version: '1.0.1'
systemName: 'PlanetHoster'
description: '.'
clientAreaName: 'PlanetHoster'
clientAreaController: Home
adminAreaController: Home
author: '<a href="https://www.modulesgarden.com" target="_blank">ModulesGarden</a>'
moduleIcon: 'modulesgarden_base'
debug: false
#fields: https://developers.whmcs.com/addon-modules/configuration/
#  option1:
#    FriendlyName: XXX
#    Type: text
