AccessControl: false
Samples: false
Logs: false
ModuleSettings: true
RequirementsChecker: false
Queue: false
DevTools: false
Product: true
Notifier: false
MediaLibrary: false
EasyTranslator: false
AppCenter: false